# deploy/cloudbuild.yaml
steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/telegram-gemini-bot', '.']
    dir: '..'  # Points to project root

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/telegram-gemini-ai-assistant/telegram-gemini-bot']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: 
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'telegram-gemini-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/telegram-gemini-bot'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY